name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Lint pull-request
    runs-on: ubuntu-latest
    steps:
      - name: Lint PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.TOPGOLFCI_TOKEN }}

      - name: Lint branch name
        uses: lekterable/branchlint-action@2.0.0
        with:
          allowed: |
            /^(feat|fix)-/i
          errorMessage: 'Branch name must start with feat- or fix-'
