name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Lint pull-request
    uses: topgolf/lint-pr-topgolf-reusable-workflow/.github/workflows/lint-pr.yml@v1
    secrets: inherit
