name: Release Drafter

on:
  push:
    branches:
      - dev
  # pull_request event is required only for autolabeler
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml
      - name: Retrieve latest release notes name-template
        uses: wei/wget@v1
        with:
          args: -O .github/release-drafter-config.yaml https://raw.githubusercontent.com/TopGolf/.github/main/release-drafter-config.yaml
      # Drafts your next Release notes as Pull Requests are merged into "dev"
      - name: Draft Release Notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yaml
          version: ${{ steps.gitversion.outputs.majorMinorPatch }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}