name: Semantic Release

on:
  push:
    branches:
      - master
      - main
      - "*.x"
      - feat-*
      - fix-*
  workflow_dispatch:

jobs:
  # UNCOMMENT OR DELETE THE FOLLOWING AS NEEDED
  # BuildDockerImage:
  #   uses: topgolf/build-docker-topgolf-reusable-workflow/.github/workflows/build-docker.yml@v1
  #   secrets: inherit

  # UNCOMMENT OR DELETE THE FOLLOWING AS NEEDED
  # UploadGenericArtifact:
  #   runs-on: [self-hosted, linux, x64]
  #   steps:
  #     - name: Upload a generic artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: generic-artifact-some-file
  #         path: some-file.exe

  reusable-workflow:
    # UNCOMMENT OR DELETE THE FOLLOWING AS NEEDED
    # needs:
    #  - BuildDockerImage
    name: Semantic Release Reusable Workflow
    uses: topgolf/semantic-release-topgolf-reusable-workflow/.github/workflows/main-ci.yml@v4
    secrets: inherit
    # Optional: If you want to override the default version of the reusable workflow
    #           Jinja2 template, you can set the following
    # with:
    #   semantic_release_reusable_workflow_git_repo: "TopGolf/semantic-release-topgolf-reusable-workflow"
    #   semantic_release_reusable_workflow_git_ref: "v1"